### ISSUE TITLE
Crash when the game starts

### ISSUE THREAD

**Issue by Demonlinkleo** [MrCrayfish/Configured#40]
Hello, i have a problem with the latest version of the mod, here is my log

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 30/12/21 22:01
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$10814/1934546750.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$8219/71170873.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:expanded_combat.mixins.json:GameRendererMixin,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.22.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$493/1916998751.call(Unknown Source) [forge-1.16.5-36.2.22.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
-- MOD configured --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: me/shedaniel/clothconfig2/api/AbstractConfigListEntry
		at com.oroarmor.netherite_plus.ForgeNetheritePlusMod.lambda$new$3(ForgeNetheritePlusMod.java:65) ~[?:?] {re:classloading}
		at com.oroarmor.netherite_plus.ForgeNetheritePlusMod$$Lambda$4422/709216688.get(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.ModContainer.getCustomExtension(ModContainer.java:139) ~[?:?] {re:classloading}
		at com.mrcrayfish.configured.client.ClientHandler.lambda$generateConfigFactories$2(ClientHandler.java:61) ~[?:1.5.1-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
		at com.mrcrayfish.configured.client.ClientHandler$$Lambda$10694/151064268.accept(Unknown Source) ~[?:?] {}
		at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:229) ~[?:?] {re:classloading}
		at com.mrcrayfish.configured.client.ClientHandler.generateConfigFactories(ClientHandler.java:58) ~[?:1.5.1-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
		at com.mrcrayfish.configured.Configured.onLoadComplete(Configured.java:49) ~[?:1.5.1-1.16.5] {re:classloading}
		at com.mrcrayfish.configured.Configured$$Lambda$3606/94731288.accept(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$2947/199076007.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$3226/978272519.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3198/1474657733.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: configured-1.5.1-1.16.5.jar
	Failure message: Configured (configured) encountered an error during the complete event phase
		java.lang.NoClassDefFoundError: me/shedaniel/clothconfig2/api/AbstractConfigListEntry
	Mod Version: 1.5.1
	Mod Issue URL: https://github.com/MrCrayfish/Configured/issues
	Exception message: java.lang.ClassNotFoundException: me.shedaniel.clothconfig2.api.AbstractConfigListEntry
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at com.oroarmor.netherite_plus.ForgeNetheritePlusMod.lambda$new$3(ForgeNetheritePlusMod.java:65) ~[?:?] {re:classloading}
	at com.oroarmor.netherite_plus.ForgeNetheritePlusMod$$Lambda$4422/709216688.get(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.getCustomExtension(ModContainer.java:139) ~[?:?] {re:classloading}
	at com.mrcrayfish.configured.client.ClientHandler.lambda$generateConfigFactories$2(ClientHandler.java:61) ~[?:1.5.1-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.mrcrayfish.configured.client.ClientHandler$$Lambda$10694/151064268.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:229) ~[?:?] {re:classloading}
	at com.mrcrayfish.configured.client.ClientHandler.generateConfigFactories(ClientHandler.java:58) ~[?:1.5.1-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.mrcrayfish.configured.Configured.onLoadComplete(Configured.java:49) ~[?:1.5.1-1.16.5] {re:classloading}
	at com.mrcrayfish.configured.Configured$$Lambda$3606/94731288.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2947/199076007.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3226/978272519.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3198/1474657733.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5016375648 bytes (4783 MB) / 6341787648 bytes (6048 MB) up to 6341787648 bytes (6048 MB)
	CPUs: 4
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmn128M -Xmx6032M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.22.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.22
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		CyclopsCore-1.16.5-1.12.1.jar                     |Cyclops Core                  |cyclopscore                   |1.12.1              |DONE      |Manifest: NOSIGNATURE
		notenoughcrashes-4.1.2+1.16.5-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.1.2+1.16.5        |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |DONE      |Manifest: NOSIGNATURE
		GokiStats-1.16.3-1.2.13.jar                       |Goki Stats                    |gokistats                     |1.2.13              |DONE      |Manifest: NOSIGNATURE
		cgm-1.1.0-1.16.5.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.1.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.138.jar                          |Just Enough Items             |jei                           |7.7.1.138           |DONE      |Manifest: NOSIGNATURE
		SlashBlade-1.16-0.0.12.jar                        |Slash Blade                   |slashblade                    |0.0.12              |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |DONE      |Manifest: NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.0beta4.jar                  |Journeymap                    |journeymap                    |5.8.0beta4          |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.5.jar                |Traveler's Backpack           |travelersbackpack             |5.4.5               |DONE      |Manifest: NOSIGNATURE
		configured-1.5.1-1.16.5.jar                       |Configured                    |configured                    |1.5.1               |ERROR     |Manifest: NOSIGNATURE
		culinaryconstruct-forge-1.16.5-4.0.0.6.jar        |Culinary Construct            |culinaryconstruct             |1.16.5-4.0.0.6      |DONE      |Manifest: NOSIGNATURE
		ImprovedBackpacks-1.6.2.0.jar                     |Improved Backpacks            |improvedbackpacks             |1.6.2.0             |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.16.5-3.0.3.297.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.0.3.297    |DONE      |Manifest: NOSIGNATURE
		FpsReducer-forge-1.24-mc1.16.5.jar                |FPS Reducer                   |fpsreducer                    |1.24-mc1.16.5       |DONE      |Manifest: NOSIGNATURE
		KimetsuAnimation_1.16.5_ver2.jar                  |kimetsuAnimationPlayer        |kimetsuanimationplayer        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		BetterThanMending-1.6.0.jar                       |BetterThanMending             |betterthanmending             |1.6.0               |DONE      |Manifest: NOSIGNATURE
		TinkersDelight-1.16-1.8.jar                       |Tinker's Delight              |tdelight                      |1.16-1.8            |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.22-universal.jar                |Forge                         |forge                         |36.2.22             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		LostTrinkets-1.16.5-0.1.27.jar                    |Lost Trinkets                 |losttrinkets                  |0.1.27              |DONE      |Manifest: NOSIGNATURE
		netherite-plus-mod-1.4.5-1.16.5-forge.jar         |Netherite Plus                |netherite_plus                |1.4.5-1.16.5        |DONE      |Manifest: NOSIGNATURE
		tl_skin_cape_forge_1.16.5-1.19.jar                |TLSkinCape                    |tlskincape                    |1.19                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		ColossalChests-1.16.5-1.8.0.jar                   |ColossalChests                |colossalchests                |1.8.0               |DONE      |Manifest: NOSIGNATURE
		LavaClearView-1.16.2-1.1.0.jar                    |Lava Clear View               |clearview                     |1.1.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.22-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.3.2.324.jar                   |Tinkers' Construct            |tconstruct                    |3.3.2.324           |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.5.4.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.5.4        |DONE      |Manifest: NOSIGNATURE
		tinker_rapier-1.1.4-1.16.5.jar                    |Tinkers' Rapier               |tinker_rapier                 |1.1.4-1.16.5        |DONE      |Manifest: NOSIGNATURE
		Lollipop-1.16.5-3.2.9.jar                         |Lollipop                      |lollipop                      |3.2.9               |DONE      |Manifest: NOSIGNATURE
		ironfurnaces-1.16.5-2.7.7.jar                     |Iron Furnaces                 |ironfurnaces                  |2.7.7               |DONE      |Manifest: NOSIGNATURE
		MasterStats.jar                                   |Master Stats                  |master_stats_by_vecker        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.1.jar                             |betterfpsdist mod             |betterfpsdist                 |1.1                 |DONE      |Manifest: NOSIGNATURE
		playerex-1.1.8-1.16.5.jar                         |Player Ex                     |playerex                      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.152.jar                         |Mantle                        |mantle                        |1.6.152             |DONE      |Manifest: NOSIGNATURE
		levelhearts-1.16.5-2.4.0.jar                      |LevelHearts                   |levelhearts                   |2.4.0               |DONE      |Manifest: NOSIGNATURE
		simplytea-1.16.5-2.4.0.jar                        |Simply Tea                    |simplytea                     |2.4.0               |DONE      |Manifest: NOSIGNATURE
		tombstone-6.6.3-1.16.5.jar                        |Corail Tombstone              |tombstone                     |6.6.3               |DONE      |Manifest: NOSIGNATURE
		relicex-1.0.0-1.16.4.jar                          |Relic Ex                      |relicex                       |1.0.0               |DONE      |Manifest: NOSIGNATURE
		obfuscate-0.6.2-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.2               |DONE      |Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		nethers_delight-2.1.jar                           |Nethers Delight               |nethers_delight               |2.1                 |DONE      |Manifest: NOSIGNATURE
		architectury-1.27.46.jar                          |Architectury                  |architectury                  |1.27.46             |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.2.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.2.0      |DONE      |Manifest: NOSIGNATURE
		KimetsunoYaiba_1.16.5_ver35.jar                   |Kimetsunoyaiba                |kimetsunoyaiba                |1.0.0               |DONE      |Manifest: NOSIGNATURE
		farmerstea-1.16.5-1.3.jar                         |Farmer's Tea - A Compat Mod   |farmerstea                    |1.16.5-1.3          |DONE      |Manifest: NOSIGNATURE
		wings-2.0.1-1.16.5.jar                            |Wings                         |wings                         |2.0.1               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v4a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v4a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		expanded_combat-2.3.1-beta_2-1.16.5.jar           |Expanded Combat               |expanded_combat               |2.3.1-beta_2        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.57.jar                  |GeckoLib                      |geckolib3                     |3.0.57              |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.16.5-1.24.12.jar                    |Ars Nouveau                   |ars_nouveau                   |1.24.12             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 8e47e8af-7c2f-498c-b4f0-4f595ef1ff2e
	Patchouli open book context: n/a
	Suspected Mods: None
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4624
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by SirKrunk** [comment]
its the netherite plus mod, you have to choose between using configured or netherite plus

**Comment by MrCrayfish** [comment]
No, you just need to install Cloth Config API to fix the issue.
