### ISSUE TITLE
Invisible on 1.18.2

### ISSUE THREAD

**Issue by KyrDerz** [MrCrayfish/Configured#70]
It is the same as this: https://github.com/MrCrayfish/Configured/issues/55
Tho I have no idea which mod causes it. I guess any without an icon.

**Comment by MrCrayfish** [comment]
Send me your mod list or if you are running a modpack, the link to CurseForge.

**Comment by KyrDerz** [comment]
It's not really public, my private one for me and my friends. But I can send an archive or a list with mods.
The solution right now it's pretty much the same. Just starting the game directly without going into mods menu

**Comment by drakray** [comment]
My own [modList](https://pastebin.com/m9atJVix), I got that too
Opening Minecraft, opening mod menu, going to single player game, entities not visible(neither are chests nor the player)

**Comment by falxie** [comment]
I've experienced the same issue with [my modpack](https://www.curseforge.com/minecraft/modpacks/construct) with the following error at the moment I scroll in the mods screen on the main menu.

<details>
<summary>Exception caught during firing event: Cannot read field "f_46443_" because the return value of "net.minecraft.world.entity.Entity.m_20193_()" is null
</summary>

```
	Index: 22
	Listeners:
		0: NORMAL
		1: ASM: xaero.map.events.Events@b5ce9b2 worldCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		2: ASM: com.teamabnormals.blueprint.common.capability.chunkloading.ChunkLoaderEvents@6838b8cd attachChunkLoaderCap(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		3: ASM: org.infernalstudios.infernalexp.init.IECapabilities@3a2dcb37 onItemAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		4: ASM: class cjminecraft.doubleslabs.common.config.ConfigEventsHandler attachConfigCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		5: ASM: class gg.moonflower.pollen.api.sync.forge.SyncedDataManagerImpl onEvent(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		6: ASM: class net.mehvahdjukaar.supplementaries.common.events.ServerEvents onAttachTileCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		7: ASM: class vazkii.quark.base.capability.CapabilityHandler attachItemCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		8: ASM: class vazkii.quark.base.capability.CapabilityHandler attachTileCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		9: ASM: class vazkii.quark.base.capability.CapabilityHandler attachWorldCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		10: ASM: class com.simibubi.create.events.CommonEvents attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		11: ASM: vazkii.quark.content.automation.module.JukeboxAutomationModule@7cbd0413 attachCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		12: ASM: vazkii.quark.content.tools.module.AncientTomesModule@77bef932 attachRuneCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		13: ASM: top.theillusivec4.comforts.common.capability.CapabilitySleepData$CapabilityEvents@57a579a6 attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		14: ASM: tschipp.carryon.common.capabilities.event.PositionCommonEvents@1a53959f onAttachCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		15: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@20f5c4d4 attachEntitiesCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		16: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@20f5c4d4 attachStackCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		17: net.minecraftforge.eventbus.EventBus$$Lambda$4382/0x0000000800ca4940@34f9743c
		18: net.minecraftforge.eventbus.EventBus$$Lambda$4382/0x0000000800ca4940@593cf957
		19: net.minecraftforge.eventbus.EventBus$$Lambda$4382/0x0000000800ca4940@3b345eae
		20: net.minecraftforge.eventbus.EventBus$$Lambda$4382/0x0000000800ca4940@54a1551d
		21: net.minecraftforge.eventbus.EventBus$$Lambda$4382/0x0000000800ca4940@2b069321
		22: net.minecraftforge.eventbus.EventBus$$Lambda$4382/0x0000000800ca4940@154e3157
		23: ASM: top.theillusivec4.polymorph.common.CommonEventsListener@4c6ba445 attachCapabilitiesPlayer(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		24: ASM: top.theillusivec4.polymorph.common.CommonEventsListener@4c6ba445 attachCapabilitiesStack(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		25: ASM: top.theillusivec4.polymorph.common.CommonEventsListener@4c6ba445 attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
java.lang.NullPointerException: Cannot read field "f_46443_" because the return value of "net.minecraft.world.entity.Entity.m_20193_()" is null
	at TRANSFORMER/tconstruct@3.5.1.31/slimeknights.tconstruct.tools.logic.EquipmentChangeWatcher.attachCapability(EquipmentChangeWatcher.java:73)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.1.74/net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:596)
	at TRANSFORMER/forge@40.1.74/net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:590)
	at TRANSFORMER/forge@40.1.74/net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:73)
	at TRANSFORMER/forge@40.1.74/net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:68)
	at TRANSFORMER/forge@40.1.74/net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:52)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Entity.<init>(Entity.java:257)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:232)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Mob.<init>(Mob.java:116)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.PathfinderMob.<init>(PathfinderMob.java:14)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.AgeableMob.<init>(AgeableMob.java:28)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.animal.Animal.<init>(Animal.java:40)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.TamableAnimal.<init>(TamableAnimal.java:29)
	at TRANSFORMER/alexsmobs@1.18.6/com.github.alexthe666.alexsmobs.entity.EntityGrizzlyBear.<init>(EntityGrizzlyBear.java:114)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:460)
	at TRANSFORMER/alexsmobs@1.18.6/com.github.alexthe666.alexsmobs.client.render.AMItemstackRenderer.m_108829_(AMItemstackRenderer.java:318)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:159)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.entity.ItemRenderer.m_115127_(ItemRenderer.java:258)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.entity.ItemRenderer.m_115123_(ItemRenderer.java:235)
	at TRANSFORMER/catalogue@1.6.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen$ModEntry.m_6311_(CatalogueModListScreen.java:764)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.AbstractSelectionList.m_93451_(AbstractSelectionList.java:466)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.AbstractSelectionList.m_6305_(AbstractSelectionList.java:201)
	at TRANSFORMER/catalogue@1.6.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen$ModList.m_6305_(CatalogueModListScreen.java:687)
	at TRANSFORMER/catalogue@1.6.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.drawModList(CatalogueModListScreen.java:273)
	at TRANSFORMER/catalogue@1.6.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.m_6305_(CatalogueModListScreen.java:191)
	at TRANSFORMER/forge@40.1.74/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:403)
	at TRANSFORMER/forge@40.1.74/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:890)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.74/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
```
</details>

**Comment by MrCrayfish** [comment]
The cause is still Alex Mob's. I've already submitted a fix and it's been merged but that version of the mod has not been released yet.

**Comment by falxie** [comment]
It seems like Alex's Mobs won't be updated for 1.18.2 at least in terms of new content, so I'm unsure if this will ever be fixed on that side.

**Comment by Kanzaji** [comment]
@MrCrayfish I was able to reproduce the issue without Alex Mobs in 1.19.2 >.> Do you have any idea if this would be possible to fix on Configured / Catalouge end?
The pack in question is Enigmatica 9 Develop, here is the link to the modlist I was testing with:
https://github.com/Kanzaji/Enigmatica9/blob/2a82b608e27e1600e9b9736e29eaa7f6b87c4dd6/MODLIST.md
Using Forge: 43.2.6
